#
# Makefile for the Novatek NT36532E touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_NT36532E_SPI) += nt36532e_ts.o
nt36532e_ts-y := nt36xxx.o nt36xxx_fw_update.o
